services:
  keycloak:
    command: start --optimized
    environment:
      KC_HOSTNAME: ${AUTH_DOMAIN}
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false

  control-plane:
    image: ghcr.io/provision-labs/provisionhub/control-plane:${CP_IMAGE_TAG:-latest}  # pull from registry instead of building
    build: !reset {}